// Данные и справочники для фермы
import { GameState, CropType, AnimalType, ProductType, Season } from "../types/farm"

export const initialGameState: GameState = {
  coins: 150,
  gems: 5,
  day: 1,
  season: "Весна",
  timeOfDay: "День",
  weather: "Солнечно",
  farmLevel: 1,
  experience: 0,
  experienceToNextLevel: 100,
  plots: Array.from({ length: 12 }, (_, i) => ({
    id: i,
    unlocked: i < 4,
    price: 50 * (i + 1),
    hasCrop: false,
    fertility: 3,
    hasProtection: false,
  })),
  inventory: [
    {
      name: "Семена пшеницы",
      quantity: 5,
      price: 5,
      sellPrice: 2,
      type: "seed",
      description: "Базовая культура, быстро растет",
      rarity: "Обычный",
    },
    {
      name: "Семена моркови",
      quantity: 3,
      price: 8,
      sellPrice: 3,
      type: "seed",
      description: "Средний срок созревания",
      rarity: "Обычный",
    },
    {
      name: "Лейка",
      quantity: 1,
      price: 15,
      sellPrice: 5,
      type: "tool",
      description: "Ускоряет рост растений",
      rarity: "Обычный",
    },
    {
      name: "Счастливая подкова",
      quantity: 1,
      price: 50,
      sellPrice: 20,
      type: "special",
      description: "Приносит удачу и увеличивает шанс редких находок",
      rarity: "Необычный",
    },
  ],
  animals: [],
  messages: ["Добро пожаловать на вашу ферму! Начните с посадки семян на доступных участках."],
  marketPrices: {
    Пшеница: 10,
    Морковь: 15,
    Картофель: 20,
    Кукуруза: 25,
    Помидоры: 30,
    Клубника: 40,
    Тыква: 35,
    Арбуз: 45,
    Подсолнух: 22,
    Яйца: 5,
    Молоко: 15,
    Шерсть: 25,
    Мясо: 40,
    Мед: 50,
    Кожа: 30,
    Курица: 50,
    Корова: 200,
    Овца: 150,
    Свинья: 180,
    Кролик: 80,
    Пчелы: 250,
    Лейка: 15,
    Удобрение: 30,
    Комбайн: 100,
    Трактор: 500,
    Теплица: 300,
    Пугало: 120,
  },
  achievements: {
    "Первый урожай": false,
    Животновод: false,
    "Богатый фермер": false,
    "Мастер фермы": false,
    Коллекционер: false,
    "Погодный маг": false,
    Счастливчик: false,
    Трудоголик: false,
    "Эксперт по животным": false,
    "Король урожая": false,
  },
  quests: [
    {
      id: 1,
      title: "Первые шаги",
      description: "Соберите 5 единиц пшеницы",
      type: "Урожай",
      target: "Пшеница",
      amount: 5,
      progress: 0,
      reward: {
        coins: 50,
        experience: 20,
        items: [{ name: "Семена картофеля", quantity: 3, type: "seed" }],
      },
      completed: false,
    },
    {
      id: 2,
      title: "Начинающий фермер",
      description: "Достигните 2 уровня фермы",
      type: "Уровень",
      target: "Уровень",
      amount: 2,
      progress: 1,
      reward: {
        coins: 100,
        experience: 30,
        items: [{ name: "Удобрение", quantity: 1, type: "tool" }],
      },
      completed: false,
    },
  ],
  activeEvents: [],
  streak: 0,
  specialUnlocks: [],
  lastSaved: Date.now(),
}

export const cropData: {
  [key in CropType]: {
    growthTime: number
    harvestYield: string
    sellPrice: number
    seedPrice: number
    seasonBonus: Season
    minLevel: number
    waterNeed: number
    fertilizerNeed: number
    rarity: "Обычный" | "Необычный" | "Редкий" | "Эпический" | "Легендарный"
  }
} = {
  Пшеница: {
    growthTime: 3,
    harvestYield: "Пшеница",
    sellPrice: 10,
    seedPrice: 5,
    seasonBonus: "Лето",
    minLevel: 1,
    waterNeed: 2,
    fertilizerNeed: 2,
    rarity: "Обычный",
  },
  Морковь: {
    growthTime: 4,
    harvestYield: "Морковь",
    sellPrice: 15,
    seedPrice: 8,
    seasonBonus: "Весна",
    minLevel: 1,
    waterNeed: 3,
    fertilizerNeed: 2,
    rarity: "Обычный",
  },
  Картофель: {
    growthTime: 5,
    harvestYield: "Картофель",
    sellPrice: 20,
    seedPrice: 10,
    seasonBonus: "Осень",
    minLevel: 2,
    waterNeed: 2,
    fertilizerNeed: 3,
    rarity: "Обычный",
  },
  Кукуруза: {
    growthTime: 6,
    harvestYield: "Кукуруза",
    sellPrice: 25,
    seedPrice: 12,
    seasonBonus: "Лето",
    minLevel: 2,
    waterNeed: 4,
    fertilizerNeed: 3,
    rarity: "Необычный",
  },
  Помидоры: {
    growthTime: 7,
    harvestYield: "Помидоры",
    sellPrice: 30,
    seedPrice: 15,
    seasonBonus: "Лето",
    minLevel: 3,
    waterNeed: 4,
    fertilizerNeed: 4,
    rarity: "Необычный",
  },
  Клубника: {
    growthTime: 8,
    harvestYield: "Клубника",
    sellPrice: 40,
    seedPrice: 20,
    seasonBonus: "Весна",
    minLevel: 3,
    waterNeed: 5,
    fertilizerNeed: 3,
    rarity: "Необычный",
  },
  Тыква: {
    growthTime: 10,
    harvestYield: "Тыква",
    sellPrice: 35,
    seedPrice: 18,
    seasonBonus: "Осень",
    minLevel: 4,
    waterNeed: 3,
    fertilizerNeed: 5,
    rarity: "Редкий",
  },
  Арбуз: {
    growthTime: 12,
    harvestYield: "Арбуз",
    sellPrice: 45,
    seedPrice: 25,
    seasonBonus: "Лето",
    minLevel: 5,
    waterNeed: 5,
    fertilizerNeed: 4,
    rarity: "Редкий",
  },
  Подсолнух: {
    growthTime: 9,
    harvestYield: "Подсолнух",
    sellPrice: 22,
    seedPrice: 14,
    seasonBonus: "Лето",
    minLevel: 4,
    waterNeed: 3,
    fertilizerNeed: 2,
    rarity: "Необычный",
  },
}

export const animalData: {
  [key in AnimalType]: {
    product: ProductType
    productionRate: number
    feedCost: number
    price: number
    minLevel: number
    happiness: number
    rarity: "Обычный" | "Необычный" | "Редкий" | "Эпический" | "Легендарный"
  }
} = {
  Курица: {
    product: "Яйца",
    productionRate: 1,
    feedCost: 2,
    price: 50,
    minLevel: 1,
    happiness: 70,
    rarity: "Обычный",
  },
  Корова: {
    product: "Молоко",
    productionRate: 2,
    feedCost: 5,
    price: 200,
    minLevel: 2,
    happiness: 60,
    rarity: "Обычный",
  },
  Овца: {
    product: "Шерсть",
    productionRate: 3,
    feedCost: 4,
    price: 150,
    minLevel: 3,
    happiness: 65,
    rarity: "Необычный",
  },
  Свинья: {
    product: "Мясо",
    productionRate: 4,
    feedCost: 6,
    price: 180,
    minLevel: 4,
    happiness: 55,
    rarity: "Необычный",
  },
  Кролик: {
    product: "Кожа",
    productionRate: 2,
    feedCost: 3,
    price: 80,
    minLevel: 3,
    happiness: 75,
    rarity: "Редкий",
  },
  Пчелы: {
    product: "Мед",
    productionRate: 3,
    feedCost: 2,
    price: 250,
    minLevel: 5,
    happiness: 80,
    rarity: "Редкий",
  },
} 